version: "3.5"

services:
  mongo:
    image: mongo:5.0.3
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ROOT_PASSWORD}"
    volumes:
      - mongo-data:/data/db
    restart: always

  producer:
    build: .
    environment:
      MONGO_ROOT_USERNAME: root
      MONGO_ROOT_PASSWORD: "${MONGO_ROOT_PASSWORD}"
      MONGODB_SERVICE_HOST: mongo
      MONGODB_SERVICE_PORT: 27017
      CLIENT_ID: "${REDDIT_CLIENT_ID}"
      CLIENT_SECRET: "${REDDIT_CLIENT_SECRET}"
      PYTHONUNBUFFERED: 1
    volumes:
      - ./:/usr/src/app
    depends_on:
      - mongo

volumes:
  mongo-data:
    name: mongo
